version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.GITHUB_TOKEN}}
  npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
    token: ${{ secrets.NPM_TOKEN }}
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    registries:
    - npm-github
    - npmjs
    schedule:
      interval: 'daily'
    assignees:
    - 'tjsr'
    groups:
      prisma:
        applies-to: version-updates
        patterns:
        - "prisma*
        - "@prisma/*"
      linter:
        applies-to: version-updates
        patterns:
        - "@typescript-eslint/*"
        - "eslint-*"
        - "@tjsr/eslint-config"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    assignees:
      - 'tjsr'
