services:
  abseedb:
    container_name: absee_mysqldb
    build:
      args:
        MYSQL_VERSION: ${MYSQL_CI_VERSION:-5.7}
      context: .
      dockerfile_inline: |
        ARG MYSQL_VERSION 5.7
        FROM mysql:${MYSQL_VERSION:-5.7} as mysql

        RUN --mount=type=cache,target=/var/cache/yum yum install -y -q gettext

        COPY scripts/api-db-users.sh /docker-entrypoint-initdb.d/010-api-db-users.sh
        COPY scripts/privs.api.template /docker-entrypoint-initdb.d/privs.api.template
        COPY scripts/030-sqlmode.sql /docker-entrypoint-initdb.d/030-sqlmode.sql
        COPY scripts/my.cnf /etc/mysql/my.cnf

        RUN chmod 700 /docker-entrypoint-initdb.d/010-api-db-users.sh
    env_file:
    - ./.env.test
    ports:
    - "${MYSQL_CI_HOST_PORT:-23507}:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysql -h 127.0.0.1 --silent -u$$MYSQL_USER -p$$MYSQL_PASSWORD", "-e", "SELECT 1"]
      interval: 3s
      retries: 5
      start_period: 30s
      
  abseedbold:
    image: mysql:5.7.18
    restart: always
    environment:
      MYSQL_DATABASE: absee_dev
      MYSQL_USER: absee_dev_user
      MYSQL_ROOT_USER: absee_dev_root
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
    - 3136:3306
    volumes:
      - absee_db_data:/var/lib/mysql

  cidbmig:
    container_name: absee_prismamig
    volumes:
    - ./prisma:/opt/migrator/prisma
    image: public.ecr.aws/tjsrowe/prisma-generic:5.20.0
    env_file:
      - path: ./.env.test
        required: true
    depends_on:
      abseedb:
        condition: service_healthy

volumes:
  absee_db_data:
