services:
  abseedb:
    container_name: absee_mysqldb
    build:
      args:
        MYSQL_VERSION: ${MYSQL_CI_VERSION:-5.7}
      context: .
      dockerfile_inline: |
        ARG MYSQL_VERSION 5.7
        FROM mysql:${MYSQL_VERSION:-5.7} AS mysql

        RUN --mount=type=cache,target=/var/cache/yum yum install -y -q gettext

        COPY --chown=mysql:mysql --chmod=750 scripts/api-db-users.sh /docker-entrypoint-initdb.d/010-api-db-users.sh
        COPY --chown=mysql:mysql --chmod=640 scripts/privs.api.template /docker-entrypoint-initdb.d/privs.api.template
        COPY --chown=mysql:mysql --chmod=640 scripts/030-sqlmode.sql /docker-entrypoint-initdb.d/030-sqlmode.sql
        COPY --chown=mysql:mysql --chmod=640 scripts/my.cnf /etc/mysql/my.cnf
        RUN touch /var/run/020-privs.api.sql && \
          ln -s /var/run/020-privs.api.sql /docker-entrypoint-initdb.d/020-privs.api.sql && \
          chown mysql:mysql /var/run/020-privs.api.sql && \
          chmod 660 /var/run/020-privs.api.sql
    env_file:
    - ./.env.test
    ports:
    - "${MYSQL_CI_HOST_PORT:-23507}:3306"
    volumes:
    - ./data/mysql_schema.sql:/docker-entrypoint-initdb.d/051-mysql_schema.sql:ro
    - ./data/mysql_data.sql:/docker-entrypoint-initdb.d/052-mysql_data.sql:ro
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysql -h 127.0.0.1 --silent -u$$MYSQL_USER -p$$MYSQL_PASSWORD", "-e", "SELECT 1"]
      interval: 3s
      retries: 5
      start_period: 30s

  cidbmig:
    container_name: absee_prismamig
    volumes:
    - ./prisma:/opt/migrator/prisma
    image: public.ecr.aws/tjsrowe/prisma-generic:6.1.0
    env_file:
      - path: ./.env.test
        required: true
    depends_on:
      abseedb:
        condition: service_healthy

volumes:
  absee_db_data:
