name: Build A/B See
run-name: ${{ github.actor }} Running A/B See build.
on: [push]
jobs:
  build-absee:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      DBMIGRATE_IMAGE: tjsrowe/absee:dbmigrate-${{ github.sha }}
      API_IMAGE: tjsrowe/absee:${{ github.sha }}

    steps:
    - name: Check out repositofy code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Amazon ECR Public
      id: login-ecr-public
      if: ${{ github.actor != 'dependabot[bot]' }}
      uses: aws-actions/amazon-ecr-login@v2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      with:
        registry-type: public

    - name: Build dbmigrate image
      uses: docker/build-push-action@v6
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        secrets: |
          github=${{ secrets.GITHUB_TOKEN }}
        file: Dockerfile.dbmigrate
        push: ${{ github.actor != 'dependabot[bot]' }}
        tags: ${{ github.actor != 'dependabot[bot]' && format('{0}/', steps.login-ecr-public.outputs.registry) || ''}}${{ env.DBMIGRATE_IMAGE }}
        cache-from: type=gha
        cache-to: type=gha

    - name: Pull patched node image
      run: |
        docker pull ghcr.io/tjsr/node_patched_npm:20.18.1-alpine3.20-npm11.0.0
  
    - name: Build API image
      uses: docker/build-push-action@v6
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        secrets: |
          github=${{ secrets.GITHUB_TOKEN }}
        file: Dockerfile
        push: ${{ github.actor != 'dependabot[bot]' }}
        tags: ${{ github.actor != 'dependabot[bot]' && format('{0}/', steps.login-ecr-public.outputs.registry) || ''}}${{ env.API_IMAGE }}
        cache-from: type=gha
        cache-to: type=gha
