name: Build A/B See
run-name: ${{ github.actor }} Running A/B See build.
on: [push]
jobs:
  build-absee:
    runs-on: ubuntu-latest
    env:
      DB_IMAGE_NAME: tjsrowe/absee-dbmigrate:${{ github.sha }}
      IMAGE_NAME: tjsrowe/absee:${{ github.sha }}
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      REGISTRY_ALIAS: tjsrowe
      REPOSITORY: absee
      IMAGE_TAG: ${{ github.sha }}

    steps:
    - name: Check out repositofy code
      uses: actions/checkout@v3
    - name: Build dbmigrate docker image
      run: |
        docker build -f Dockerfile.dbmigrate -t $DB_IMAGE_NAME .
        docker tag $DB_IMAGE_NAME absee-dbmigrate:${{ github.sha }}
    - name: Build API docker image
      run: |
        docker build -f Dockerfile -t $IMAGE_NAME .
        docker tag $IMAGE_NAME absee:${{ github.sha }}
    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      with:
        registry-type: public
        aws-region: us-east-1

    - name: Build, tag, and push docker image to Amazon ECR Public
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
      run: |
        docker tag $IMAGE_NAME $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
        docker tag $IMAGE_NAME $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest-dev
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest-dev
  
name: Deploy dev
run-name: ${{ github.actor }} Deploy A/B See dev build.
jobs:
  deployment:
  runs-on: ubuntu-latest
    environment: dev
    url: https://dev.pinpare.com
    env:
      DB_IMAGE_NAME: tjsrowe/absee-dbmigrate:${{ github.sha }}
      IMAGE_NAME: tjsrowe/absee:${{ github.sha }}
    steps:
    - name: Add known host
      run: ssh-keyscan -H ${{ secrets.DEPLOYMENT_HOST }} >> ~/.ssh/known_hosts
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
        known_hosts: 'placeholder'
      name: Pull docker containers to dev server
      run: |
        ssh ${{ secrets.DEPLOYMENT_USER }}@${{ secrets.DEPLOYMENT_USER }} docker pull public.ecr.aws/$DB_IMAGE_NAME
        ssh ${{ secrets.DEPLOYMENT_USER }}@${{ secrets.DEPLOYMENT_USER }} docker pull public.ecr.aws/$IMAGE_NAME

