name: Build A/B See
run-name: ${{ github.actor }} Running A/B See build.
on: [push]
jobs:
  build-absee:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
      DB_IMAGE_TAG: dbmigrate-${{ github.sha }}
      IMAGE_NAME: absee:${{ github.sha }}
      DB_IMAGE_NAME: absee:dbmigrate-${{ github.sha }}
      DOCKER_BUILDKIT: 1
      BUILDKIT_PROGRESS: plain
      REGISTRY_ALIAS: tjsrowe
      REPOSITORY: absee

    steps:
    - name: Identify output images
      id: imgid
      run: |
        echo "dbmigrate_tag=$DB_IMAGE_TAG" >> $GITHUB_ENV
        echo "api_tag=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Check out repositofy code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-single-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-single-buildx

    - name: Build dbmigrate image
      uses: docker/build-push-action@v2
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: Dockerfile.dbmigrate
        push: false
        tags: ${{ env.dbmigrate_tag }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new

    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ECR_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ECR_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      with:
        registry-type: public
        aws-region: us-east-1

    - name: Tag dbmigrate docker image for ECR public    
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
      run: |
        docker tag $DB_IMAGE_TAG $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$DB_IMAGE_TAG

    - name: Build API image
      uses: docker/build-push-action@v2
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: Dockerfile
        push: false
        tags: ${{ env.api_tag }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache-new
      
    - name: Tag API docker image for ECR public    
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
      run: |
        docker tag $IMAGE_TAG $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
        docker tag $IMAGE_TAG $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest-dev
    
    - name: Build, tag, and push docker image to Amazon ECR Public
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
      run: |
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:latest-dev

    - name: Build, tag, and push docker DB Migration image to Amazon ECR Public
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
      run: |
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$DB_IMAGE_TAG

  