name: Deploy dev
# run-name: ${{ github.actor }} Deploy A/B See dev build.
on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://dev.pinpare.com
    env:
      IMAGE_TAG: ${{ github.sha }}
      DB_IMAGE_TAG: dbmigrate-${{ github.sha }}
      IMAGE_NAME: absee:${{ github.sha }}
      DB_IMAGE_NAME: absee:dbmigrate-${{ github.sha }}
      REGISTRY_ALIAS: tjsrowe
      REPOSITORY: absee
    steps:
    - name: Pull DB deploy image on remote.
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.DEPLOYMENT_HOST }}
        username: ${{ secrets.DEPLOYMENT_USER }}
        key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
        envs: DB_IMAGE_NAME,IMAGE_NAME
        script: |
          docker pull public.ecr.aws/$REGISTRY_ALIAS/$DB_IMAGE_NAME
          docker pull public.ecr.aws/$REGISTRY_ALIAS/$IMAGE_NAME
          docker tag public.ecr.aws/$REGISTRY_ALIAS/$DB_IMAGE_NAME $IMAGE_NAME
          docker tag public.ecr.aws/$REGISTRY_ALIAS/$DB_IMAGE_NAME $DB_IMAGE_NAME

