name: Deploy dev
# run-name: ${{ github.actor }} Deploy A/B See dev build.
on: [workflow_dispatch]

jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    environment: dev
#    url: https://dev.pinpare.com
    env:
      DB_IMAGE_NAME: tjsrowe/absee-dbmigrate:${{ github.sha }}
      IMAGE_NAME: tjsrowe/absee:${{ github.sha }}
    steps:
    - name: Add known host
      run: ssh-keyscan -H ${{ secrets.DEPLOYMENT_HOST }} >> ~/.ssh/known_hosts
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
        known_hosts: 'placeholder'
    - name: Pull docker containers to dev server
      run: |
        ssh ${{ secrets.DEPLOYMENT_USER }}@${{ secrets.DEPLOYMENT_USER }} docker pull public.ecr.aws/$DB_IMAGE_NAME
        ssh ${{ secrets.DEPLOYMENT_USER }}@${{ secrets.DEPLOYMENT_USER }} docker pull public.ecr.aws/$IMAGE_NAME

