name: Deploy dev
# run-name: ${{ github.actor }} Deploy A/B See dev build.
on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://dev.pinpare.com
    env:
      IMAGE_TAG: ${{ github.sha }}
      DB_IMAGE_TAG: dbmigrate-${{ github.sha }}
      IMAGE_NAME: absee:${{ github.sha }}
      DB_IMAGE_NAME: absee:dbmigrate-${{ github.sha }}
      REGISTRY_ALIAS: tjsrowe
      REPOSITORY: absee
      PRISMA_DATABASE_URL: ${{ secrets.PRISMA_DATABASE_URL }}
      CONTAINER_NAME: ${{ env.CONTAINER_NAME }}
      API_PORT: ${{ env.API_PORT }}
    steps:
    - name: Pull DB deploy image on remote.
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.DEPLOYMENT_HOST }}
        username: ${{ secrets.DEPLOYMENT_USER }}
        key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
        envs: DB_IMAGE_NAME,IMAGE_NAME,REGISTRY_ALIAS,PRISMA_DATABASE_URL,CONTAINER_NAME,API_PORT
        script: |
          docker pull public.ecr.aws/$REGISTRY_ALIAS/$DB_IMAGE_NAME
          docker pull public.ecr.aws/$REGISTRY_ALIAS/$IMAGE_NAME
          docker tag public.ecr.aws/$REGISTRY_ALIAS/$DB_IMAGE_NAME $IMAGE_NAME
          docker tag public.ecr.aws/$REGISTRY_ALIAS/$DB_IMAGE_NAME $DB_IMAGE_NAME
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true
          docker run -e PRISMA_DATABASE_URL=$PRISMA_DATABASE_URL --rm --name absee-migrate -t $DB_IMAGE_NAME
          docker run --name $CONTAINER_NAME --restart=always -p $API_PORT:8280 --env-file=/home/ec2-user/absee/.env.dev -d -t $IMAGE_NAME


