name: Deploy dev
# run-name: ${{ github.actor }} Deploy A/B See dev build.
on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: dev
      url: https://dev.pinpare.com
    env:
      DB_IMAGE_NAME: tjsrowe/absee-dbmigrate:${{ github.sha }}
      IMAGE_NAME: tjsrowe/absee:${{ github.sha }}
    steps:
    - name: Pull DB deploy image on remote.
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.DEPLOYMENT_HOST }}
        username: ${{ secrets.DEPLOYMENT_USER }}
        key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
        script: |
          docker pull public.ecr.aws/$DB_IMAGE_NAME
          docker pull public.ecr.aws/$IMAGE_NAME

